### ISSUE TITLE
Find alternative methods of serializing tfx.graph

### ISSUE THREAD

**Issue by destefy** [CentML/centml-python-client#10]
┆Issue is synchronized with this [Notion page](https://www.notion.so/Find-alternative-methods-of-serializing-tfx-graph-a718a19866ec49739abfeea6b3090ea8) by [Unito](https://www.unito.io)

**Comment by destefy** [comment]
Understand what is the severity of this problem
- What would cause a failure?

**Comment by destefy** [comment]
My findings:

Firstly, it’s important to remember that there’s lots of ways to convert a python object into a byte stream. When we’re hashing, we want the byte stream to be consistent so the hash is consistent. However, when serializing to send the model between client and server, we don’t care if the byte stream is the same, just if it can successfully be unpickled into the original object.
Findings:
- Pickling in python3.9 and unpickling in python3.12/3.11 seemed to work find. This is expected because pickle doesn’t overwrite old opcodes. Even when they improve the opcodes, the old ocodes are still known. Therefore, when a newer python version if given a old python file it can still make sense of it.
- However, when I pickle in python3.11 (python3.12 doesn’t support torch dynamo) and unpickle in python3.9, it get an error message: `AttributeError: 'FrameSummary' object has no attribute 'end_lineno'` . end_lineno is an attribute for the python `FrameSummary` that was added in version 3.10 ([[https://docs.python.org/3/library/traceback.html#traceback.TracebackException.end_lineno:~:text=end_lineno-,¶,-For](https://docs.python.org/3/library/traceback.html#traceback.TracebackException.end_lineno:~:text=end_lineno-,%C2%B6,-For) syntax errors](https://docs.python.org/3/library/traceback.html#traceback.TracebackException.end_lineno:~:text=end_lineno-,%C2%B6,-For%20syntax%20errors))
- Therefore, this error is not a pickling issue but instead a python version issue.
- However, I would expect that makes sense that unpickling in an older environment would fail, because the new pickle version may be using opcodes that the old versions don’t have implemented (tho that’s not why this example is failing)
- Also, in the previous example, using torch.load/save or pickle.load/dump made no difference. This makes sense because [[torch.s](http://torch.save/)](http://torch.save)ave/load uses pickle under the hood.

**Comment by anandj91** [comment]
@destefy I believe we can close this ticket. torch.save() should be the best serializer for fx.graph. If you agree, please close the ticket.
